import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Context from "./Context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Grocery",
    template:"%s | Grocery"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Context>
            {children}
          
          
        </Context>
        
      </body>
    </html>
  );
}
